name: Build

on: 
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      run: |
        wget -O- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main"
        # Workaround for issue https://github.com/llvm/llvm-project/issues/133861
        sudo ln -s /usr/lib/llvm-22/lib /usr/lib/lib
        sudo ln -s /usr/lib/llvm-22/include /usr/lib/include
        sudo apt-get update
        sudo apt-get install ninja-build llvm-22-dev

    - name: Compile
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja
        cmake --build . -j

